// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBDZwYsnCVJOiIODLZ-f9JQrTv7ST_vkE',
    appId: '1:976261385108:web:4cc067de88f451c7a19d81',
    messagingSenderId: '976261385108',
    projectId: 'sparkchat-f1797',
    authDomain: 'sparkchat-f1797.firebaseapp.com',
    storageBucket: 'sparkchat-f1797.firebasestorage.app',
    measurementId: 'G-EJFFKBXSE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5UwKK-TrBDz7dEAYbALIeht0GpZAFFZ8',
    appId: '1:976261385108:android:628e7a96e12f9ca6a19d81',
    messagingSenderId: '976261385108',
    projectId: 'sparkchat-f1797',
    storageBucket: 'sparkchat-f1797.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDqfB_P-lawVJfjZIvaFl3iXPB0nmaVWA',
    appId: '1:976261385108:ios:42306e0aca32715aa19d81',
    messagingSenderId: '976261385108',
    projectId: 'sparkchat-f1797',
    storageBucket: 'sparkchat-f1797.firebasestorage.app',
    iosBundleId: 'com.example.npjWhatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDqfB_P-lawVJfjZIvaFl3iXPB0nmaVWA',
    appId: '1:976261385108:ios:42306e0aca32715aa19d81',
    messagingSenderId: '976261385108',
    projectId: 'sparkchat-f1797',
    storageBucket: 'sparkchat-f1797.firebasestorage.app',
    iosBundleId: 'com.example.npjWhatsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBDZwYsnCVJOiIODLZ-f9JQrTv7ST_vkE',
    appId: '1:976261385108:web:65d7cb678efe2ec7a19d81',
    messagingSenderId: '976261385108',
    projectId: 'sparkchat-f1797',
    authDomain: 'sparkchat-f1797.firebaseapp.com',
    storageBucket: 'sparkchat-f1797.firebasestorage.app',
    measurementId: 'G-XMFFJY3ZWH',
  );
}
