// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt6jFNtSXmawai4diEYcXqieQHZ27omQE',
    appId: '1:639935316224:web:13d99a2afcfab71f7473e5',
    messagingSenderId: '639935316224',
    projectId: 'agro-app-65d1f',
    authDomain: 'agro-app-65d1f.firebaseapp.com',
    storageBucket: 'agro-app-65d1f.firebasestorage.app',
    measurementId: 'G-B7ZE4FBM0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu4r8td99811rU-1704Cq1DHFPhs1umhc',
    appId: '1:639935316224:android:9d376e042c0025397473e5',
    messagingSenderId: '639935316224',
    projectId: 'agro-app-65d1f',
    storageBucket: 'agro-app-65d1f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCgNrd1SEzqCeF0vca15Rn5fqIFwJFJWc',
    appId: '1:639935316224:ios:0bd589f664e3369f7473e5',
    messagingSenderId: '639935316224',
    projectId: 'agro-app-65d1f',
    storageBucket: 'agro-app-65d1f.firebasestorage.app',
    iosBundleId: 'com.example.agroApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCgNrd1SEzqCeF0vca15Rn5fqIFwJFJWc',
    appId: '1:639935316224:ios:0bd589f664e3369f7473e5',
    messagingSenderId: '639935316224',
    projectId: 'agro-app-65d1f',
    storageBucket: 'agro-app-65d1f.firebasestorage.app',
    iosBundleId: 'com.example.agroApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt6jFNtSXmawai4diEYcXqieQHZ27omQE',
    appId: '1:639935316224:web:ea5460f155cea0d77473e5',
    messagingSenderId: '639935316224',
    projectId: 'agro-app-65d1f',
    authDomain: 'agro-app-65d1f.firebaseapp.com',
    storageBucket: 'agro-app-65d1f.firebasestorage.app',
    measurementId: 'G-08C978P16P',
  );
}
